project:
  type: website
  output-dir: docs

website:
  title: "Disease modeling for public health"
  site-url: https://kimfinale.github.io/myblog/
  description: "Disease modeling for public health"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kimfinale
      - icon: twitter
        href: https://twitter.com/tarzanthoreau
format:
  html:
    theme: solar
    css: styles.css

editor: visual


