# Jong-Hoon Kim

|                            |                      |
|:---------------------------|:---------------------|
| 101-1804                   | kimfinale\@gmail.com |
| 174 Solsaem-ro, Gangbuk-gu | www.jonghoonk.com    |
| Seoul, Korea               | +82-10-9482-2517     |

## EDUCATION

2021-2023 (expected)

:   **MicroMaster, Statistics and Data Science**; MITx (online learning initiative of the Massachusetts Institute of Technology)

2006-2010

:   **PhD, Theoretical Epidemiology (Disease Transmission Modeling)**; University of Michigan, Ann Arbor

    *Thesis title: Dynamic partnerships and HIV transmissions by stage*

2007-2010

:   **MSc, Biophysics and molecular biology**; Gwangju Institute of Science and Technology

2007-2010

:   **BSc, Biochemistry**; Chungnam National University

## HONORS AND AWARDS

2008-9\
**Rackham Fellowship (\$20,000)** University of Michigan, Ann Arbor 2004 **Student Award (\$3,000)**\
Blue Cross Blue Shield Michigan Foundation 2003-2004 **Study Abroad Scholarship (\$60,000)** Korea Science and Engineering Foundation

## EXPERIENCE

**Your Most Recent Work Experience:**

Short text containing the type of work done, results obtained, lessons learned and other remarks. Can also include lists and links:

-   First item

-   Item with [link](http://www.example.com). Links will work both in the html and pdf versions.

**That Other Job You Had**

Also with a short description.

## CURRENT POSITION

Research Scientist at the International Vaccine Institute (2018-present)

## RESEARCH INTERESTS

I am a theoretical epidemiologist specializing in the modeling of infectious disease transmission. My research involves utilizing mathematical and statistical models as well as data science techniques to examine the dynamics of disease transmission and evaluate the effectiveness of intervention programs like vaccination. Over the course of my career, I have investigated a wide range of pathogens including HIV, poliovirus, cholera, typhoid fever, non-typhoidal Salmonella disease, and COVID-19. To continue expanding my expertise in the field, I actively pursue new knowledge in machine learning and data science. Additionally, I have shared my knowledge through numerous lectures and participated in advisory panels aimed at controlling the spread of COVID-19 in Korea.

## Technical Experience

My Cool Side Project

:   For items which don't have a clear time ordering, a definition list can be used to have named items.

    -   These items can also contain lists, but you need to mind the indentation levels in the markdown source.
    -   Second item.

Open Source

:   List open source contributions here, perhaps placing emphasis on the project names, for example the **Linux Kernel**, where you implemented multithreading over a long weekend, or **node.js** (with [link](http://nodejs.org)) which was actually totally your idea...

Programming Languages

:   **first-lang:** Here, we have an itemization, where we only want to add descriptions to the first few items, but still want to mention some others together at the end. A format that works well here is a description list where the first few items have their first word emphasized, and the last item contains the final few emphasized terms. Notice the reasonably nice page break in the pdf version, which wouldn't happen if we generated the pdf via html.

:   **second-lang:** Description of your experience with second-lang, perhaps again including a \[link\] [ref](https://github.com/githubuser/superlongprojectname), this time placing the url reference elsewhere in the document to reduce clutter (see source file).

:   **obscure-but-impressive-lang:** We both know this one's pushing it.

:   Basic knowledge of **C**, **x86 assembly**, **forth**, **Common Lisp**

## Extra Section, Call it Whatever You Want

-   Human Languages:

    -   English (native speaker)
    -   ???
    -   This is what a nested list looks like.

-   Random tidbit

-   Other sort of impressive-sounding thing you did
